### ISSUE TITLE
Exception creating new items

### ISSUE THREAD

**Issue by rknowles9** [aristotle-mdr/aristotle-metadata-registry#1013]
Aristotle 2.2.0, Firefox 60.3
I get an exception when creating new items. This occurs when I hit the "Save" button following create new or "Save and Create" from create wizard. It does not happen every time, but about half or more of the 20 last items I've created. When I get the exception I hit the "Back" button in Firefox, then hit "Save" again and the create works; with wizard it jumps back a few steps so I re-enter, then sometimes fails a second time, then Back again and it succeeds. This has happened with Data Elements, Data Element Concepts, Properties, Object Classes (maybe others). I've attached output when the Data Element wizard failed, with some obfuscation

[AssertionError at _create_wizard_aristotle_mdr_dataelement.txt](https://github.com/aristotle-mdr/aristotle-metadata-registry/files/2605071/AssertionError.at._create_wizard_aristotle_mdr_dataelement.txt)

.

**Comment by LegoStormtroopr** [comment]
Thanks for reporting this.

I had a look at the traceback, and it seems that Whoosh is failing to update the index. Aristotle updates the search index on save to ensure that its updated as quickly as possible.

I've pasted the relevant section of the linked traceback that indicate this:

```
AssertionError at /create/wizard/aristotle_mdr/dataelement

No exception message supplied
File "/home/XXXXX/XXXXXXXX/XXXXaristotle-20181101/python-local/venv/lib64/python3.6/site-packages/whoosh/codec/base.py" in create_compound_file
  560.         assert not any(name.endswith(self.COMPOUND_EXT) for name in segfiles)
```

Without knowing more about how you've deployed this I can't offer anymore advice.
