### ISSUE TITLE
Data Elements in Data Set Specification page table misaligned

### ISSUE THREAD

**Issue by LegoStormtroopr** [aristotle-mdr/aristotle-metadata-registry#1018]
![image](https://user-images.githubusercontent.com/2173174/49419496-31c9b000-f7db-11e8-99b3-c4c0931b1c07.png)

**Comment by s-i-l-k-e** [comment]
![image](https://user-images.githubusercontent.com/38807135/72028536-fe5b2e00-32d6-11ea-85aa-7593a62be194.png)
This is no longer an issue since we moved to a unified editor, closing.
