### ISSUE TITLE
Add link to Sandbox and Profile to user menu

### ISSUE THREAD

**Issue by LegoStormtroopr** [aristotle-mdr/aristotle-metadata-registry#1021]
![image](https://user-images.githubusercontent.com/2173174/49770366-45739a00-fd38-11e8-8994-43b95ce49b3c.png)

Story 1:

* As a **user**
* I would like to **access my sandbox easily**
* So I can: **find my content easily**
* I can do this by: **using a menu item available on all sites**

Story 2:

* As a **user**
* I would like to **access my profile**
* So I can: **see my details**
* I can do this by: **using a menu item available on all sites**

To make this easier the order of the menu item, will be the same as the order in the My Dashboard sidebar.

**Comment by fragalcer** [comment]
Implemented.
