### ISSUE TITLE
Profile window crops profile image

### ISSUE THREAD

**Issue by LegoStormtroopr** [aristotle-mdr/aristotle-metadata-registry#1029]
This happens on your own profile page (/account/profile) and when viewing/editing another users profile

![image](https://user-images.githubusercontent.com/2173174/50100569-ee5c5080-0274-11e9-8e20-78d8a8f94cee.png)

**Comment by s-i-l-k-e** [comment]
Thanks for reporting @LegoStormtroopr. Fixed in 3.0.14.
