### ISSUE TITLE
Check ordering is applied correctly to roles

### ISSUE THREAD

**Issue by LegoStormtroopr** [aristotle-mdr/aristotle-metadata-registry#1033]
On this page, it should show:

All Workgroups, and a users roles ordered by Workgroup name
then
All Registration Authorities, and a users roles ordered by RA name

![image](https://user-images.githubusercontent.com/2173174/50238823-0243a780-0386-11e9-9eda-60417034fb5a.png)

**Comment by fragalcer** [comment]
FIxed this issue. Created pull request.
