### ISSUE TITLE
Unable to cancel leave workgroup request

### ISSUE THREAD

**Issue by larrn** [aristotle-mdr/aristotle-metadata-registry#1092]
On the Workgroup page, when you select "Leave Workgroup" it takes you to a page where you can select "no take me back", but instead of going back to the Workgroup page it take you to a random item page. 
![image](https://user-images.githubusercontent.com/16367069/53379625-71f59480-39be-11e9-845f-c717baf7f23f.png)
![image](https://user-images.githubusercontent.com/16367069/53379645-7fab1a00-39be-11e9-96a4-f15478fea15e.png)
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/16367069/53379655-8f2a6300-39be-11e9-9698-2059436a986c.png">

**Comment by s-i-l-k-e** [comment]
Fixed by #1446
