### ISSUE TITLE
Need warning before deleting discussion post

### ISSUE THREAD

**Issue by larrn** [aristotle-mdr/aristotle-metadata-registry#1096]
When clicking "delete post and all comments" on a discussion post there should be a warning before everything is deleted. 
![image](https://user-images.githubusercontent.com/16367069/53389332-f9ed9580-39e2-11e9-89bf-90fc7b141234.png)

**Comment by s-i-l-k-e** [comment]
![image](https://user-images.githubusercontent.com/38807135/61271382-cec7df00-a7e7-11e9-82d6-ef8ca7367ee8.png)
