### ISSUE TITLE
API Swagger test section doesn't use api URL

### ISSUE THREAD

**Issue by LegoStormtroopr** [aristotle-mdr/aristotle-metadata-registry#1104]
For example, testing the api/v4 "item" endpoint like this:
![image](https://user-images.githubusercontent.com/2173174/53538934-ae162a00-3b63-11e9-9616-df9437281844.png)

Actually pulls the item page:

![image](https://user-images.githubusercontent.com/2173174/53538953-c25a2700-3b63-11e9-9e1a-7840914ab166.png)

It should fetch `aristotle.example.com/api/v4/item/{id}` but instead fetches `aristotle.example.com/item/{id}`

**Comment by LegoStormtroopr** [comment]
@harrywhite4 this is fixed now, yeah?

**Comment by fragalcer** [comment]
Yes, this is fixed now.

**Comment by fragalcer** [comment]
> @harrywhite4 this is fixed now, yeah?

Yes, this is fixed now.
