### ISSUE TITLE
Recently viewed items delete box has no hover title

### ISSUE THREAD

**Issue by LegoStormtroopr** [aristotle-mdr/aristotle-metadata-registry#1111]
Hovering over the delete button doesn't describe what it does.

![image](https://user-images.githubusercontent.com/2173174/53703765-bb842a80-3e69-11e9-9338-455db3144f49.png)

**Comment by fragalcer** [comment]
![image](https://user-images.githubusercontent.com/31025299/67194758-7128db80-f443-11e9-9797-def2453be9ee.png)
