### ISSUE TITLE
ModuleNotFoundError: No module named 'anymail'

### ISSUE THREAD

**Issue by Rknowles0** [aristotle-mdr/aristotle-metadata-registry#1202]
Logged in as an admin.
My Dashboard => Administrator Tools => Manage Users => Invite Member
Enter email address, then 'Invite'.
Screen goes to 'WTF 500', log shows below:

`web_1            | ERROR 2019-05-02 15:13:55,559 exception 12 140698407266048 Internal Server Error: /account/registry/invitations/
web_1            | Traceback (most recent call last):
web_1            |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
web_1            |     response = get_response(request)
web_1            |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
web_1            |     response = self.process_exception_by_middleware(e, request)
web_1            |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
web_1            |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
web_1            |   File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
web_1            |     return self.dispatch(request, *args, **kwargs)
web_1            |   File "/usr/local/lib/python3.6/site-packages/braces/views/_access.py", line 102, in dispatch
web_1            |     request, *args, **kwargs)
web_1            |   File "/usr/local/lib/python3.6/site-packages/braces/views/_access.py", line 211, in dispatch
web_1            |     request, *args, **kwargs)
web_1            |   File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
web_1            |     return handler(request, *args, **kwargs)
web_1            |   File "/usr/local/lib/python3.6/site-packages/django/views/generic/edit.py", line 183, in post
web_1            |     return self.form_valid(form)
web_1            |   File "/usr/local/lib/python3.6/site-packages/aristotle_mdr/contrib/user_management/org_backends.py", line 192, in form_valid
web_1            |     self.backend.invite_by_emails(form.emails, request=self.request)
web_1            |   File "/usr/local/lib/python3.6/site-packages/aristotle_mdr/contrib/user_management/org_backends.py", line 99, in invite_by_emails
web_1            |     self.send_invitation(user, sender, request=request, **kwargs)
web_1            |   File "/usr/local/lib/python3.6/site-packages/aristotle_mdr/contrib/user_management/org_backends.py", line 153, in send_invitation
web_1            |     self.email_message(user, self.invitation_subject, self.invitation_body, **kwargs).send()
web_1            |   File "/usr/local/lib/python3.6/site-packages/django/core/mail/message.py", line 348, in send
web_1            |     return self.get_connection(fail_silently).send_messages([self])
web_1            |   File "/usr/local/lib/python3.6/site-packages/django/core/mail/message.py", line 302, in get_connection
web_1            |     self.connection = get_connection(fail_silently=fail_silently)
web_1            |   File "/usr/local/lib/python3.6/site-packages/django/core/mail/__init__.py", line 36, in get_connection
web_1            |     klass = import_string(backend or settings.EMAIL_BACKEND)
web_1            |   File "/usr/local/lib/python3.6/site-packages/django/utils/module_loading.py", line 20, in import_string
web_1            |     module = import_module(module_path)
web_1            |   File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
web_1            |     return _bootstrap._gcd_import(name[level:], package, level)
web_1            |   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
web_1            |   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
web_1            |   File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
web_1            |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
web_1            |   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
web_1            |   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
web_1            |   File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
web_1            |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
web_1            |   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
web_1            |   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
web_1            |   File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
web_1            | ModuleNotFoundError: No module named 'anymail'
web_1            | WARNING 2019-05-02 15:13:55,647 base 14 140698407266048 Not Found: /static/

`

**Comment by s-i-l-k-e** [comment]
Hi @Rknowles0, how are you running your server? If it's from the docker container _any_mail_ should be installed as part of starting up. If not, I can help you with your tailored setup.

**Comment by s-i-l-k-e** [comment]
Hi @Rknowles0, thanks for getting back to me.

The way Aristotle is configured by default is if there are no mail settings, the docker image will just print emails out to the console using django’s mail console backend.

If you would like the system to send emails you will need to add the following environment variables:
EMAIL_HOST
EMAIL_HOST_PASSWORD
EMAIL_HOST_USER
EMAIL_PORT
These use the defaults from Django, and information on what these require is available here:
[Settings](https://docs.djangoproject.com/en/1.11/ref/settings/#email-host)

**Comment by Rknowles0** [comment]
Today I tried this with docker.io/aristotlemetadata/aristotle_mdr_docker, 3.0.0rc37,           e0fb9deac7d5. Without the environment variables I still get the anymail error, just as when I opened this in May, same WTF 500 screen, same traceback.

I then added EMAIL_HOST to the environment and with that get a different error, "OSError: [Errno 97] Address family not supported by protocol":

web_1            | ERROR 2019-08-23 18:30:10,140 exception 16 140717211903744 Internal Server Error: /account/registry/invitations/
web_1            | Traceback (most recent call last):
web_1            |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
web_1            |     response = get_response(request)
web_1            |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
web_1            |     response = self.process_exception_by_middleware(e, request)
web_1            |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
web_1            |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
web_1            |   File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
web_1            |     return self.dispatch(request, *args, **kwargs)
web_1            |   File "/usr/local/lib/python3.6/site-packages/braces/views/_access.py", line 102, in dispatch
web_1            |     request, *args, **kwargs)
web_1            |   File "/usr/local/lib/python3.6/site-packages/braces/views/_access.py", line 211, in dispatch
web_1            |     request, *args, **kwargs)
web_1            |   File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
web_1            |     return handler(request, *args, **kwargs)
web_1            |   File "/usr/local/lib/python3.6/site-packages/django/views/generic/edit.py", line 183, in post
web_1            |     return self.form_valid(form)
web_1            |   File "/usr/local/lib/python3.6/site-packages/aristotle_mdr/contrib/user_management/org_backends.py", line 193, in form_valid
web_1            |     self.backend.invite_by_emails(form.emails, request=self.request)
web_1            |   File "/usr/local/lib/python3.6/site-packages/aristotle_mdr/contrib/user_management/org_backends.py", line 99, in invite_by_emails
web_1            |     self.send_invitation(user, sender, request=request, **kwargs)
web_1            |   File "/usr/local/lib/python3.6/site-packages/aristotle_mdr/contrib/user_management/org_backends.py", line 153, in send_invitation
web_1            |     self.email_message(user, self.invitation_subject, self.invitation_body, **kwargs).send()
web_1            |   File "/usr/local/lib/python3.6/site-packages/django/core/mail/message.py", line 348, in send
web_1            |     return self.get_connection(fail_silently).send_messages([self])
web_1            |   File "/usr/local/lib/python3.6/site-packages/django/core/mail/backends/smtp.py", line 104, in send_messages
web_1            |     new_conn_created = self.open()
web_1            |   File "/usr/local/lib/python3.6/site-packages/django/core/mail/backends/smtp.py", line 64, in open
web_1            |     self.connection = self.connection_class(self.host, self.port, **connection_params)
web_1            |   File "/usr/local/lib/python3.6/smtplib.py", line 251, in __init__
web_1            |     (code, msg) = self.connect(host, port)
web_1            |   File "/usr/local/lib/python3.6/smtplib.py", line 336, in connect
web_1            |     self.sock = self._get_socket(host, port, self.timeout)
web_1            |   File "/usr/local/lib/python3.6/smtplib.py", line 307, in _get_socket
web_1            |     self.source_address)
web_1            |   File "/usr/local/lib/python3.6/socket.py", line 724, in create_connection
web_1            |     raise err
web_1            |   File "/usr/local/lib/python3.6/socket.py", line 708, in create_connection
web_1            |     sock = socket(af, socktype, proto)
web_1            |   File "/usr/local/lib/python3.6/socket.py", line 144, in __init__
web_1            |     _socket.socket.__init__(self, family, type, proto, fileno)
web_1            | OSError: [Errno 97] Address family not supported by protocol
web_1            | WARNING 2019-08-23 18:30:10,209 base 16 140717211903744 Not Found: /static/

**Comment by Rknowles0** [comment]
Closed by mistake.

**Comment by Rknowles0** [comment]
Has there been any progress on this issue? Behavior today is the same as my last report on 23 Aug. When I add EMAIL_HOST and use defaults for the other three variables I get the stack trace as shown in my previous message. My searches for 'OSError: [Errno 97] Address family not supported by protocol' lead to problems with IPV4 v. IPV6. Does this have anything to do with the Docker stack, running 'web' with no external IP through 'nginx' with internal and exterrnal IPs?

**Comment by LegoStormtroopr** [comment]
I looks like this is might be an issue with a IPV6 only host.
* https://bugs.python.org/issue10414
* https://stackoverflow.com/questions/13726890/django-contact-form-mail-error-address-family-not-supported-by-protocol-request

Can you email some more details through?
