### ISSUE TITLE
500 error when deleting concepts from admin

### ISSUE THREAD

**Issue by LegoStormtroopr** [aristotle-mdr/aristotle-metadata-registry#1203]
TypeError: Object of type ModelSignal is not JSON serializable

**Comment by LegoStormtroopr** [comment]
@Rknowles0 I think you reported something similar?

**Comment by Rknowles0** [comment]
@s-i-l-k-e  - Can you tell me what the resolution was for this issue? Fixed? Documentation change? What version?  Thanks!

**Comment by LegoStormtroopr** [comment]
This should now be fixed in the develop branch, and which was packaged that up for you recently.

**Comment by Rknowles0** [comment]
Got it! Thank you.
