### ISSUE TITLE
Count of collections children is wrong

### ISSUE THREAD

**Issue by LegoStormtroopr** [aristotle-mdr/aristotle-metadata-registry#1209]
![image](https://user-images.githubusercontent.com/2173174/57204636-9b005a00-6feb-11e9-92c7-1b3251d90309.png)

0 should be the correct number

**Comment by s-i-l-k-e** [comment]
This has been fixed by the addition of a subcollection column
![image](https://user-images.githubusercontent.com/38807135/72227757-412d4680-35f4-11ea-829a-0b55c6042680.png)
