### ISSUE TITLE
Any user (not developer-oriented) documentation?

### ISSUE THREAD

**Issue by lifepillar** [aristotle-mdr/aristotle-metadata-registry#1307]
Is there any user documentation or tutorial available for this project? All I can find is http://docs.aristotlemetadata.com/.

**Comment by LegoStormtroopr** [comment]
Hi, we also have more user focused help available at https://help.aristotlemetadata.com/

If you'd like to email me, I'd be happy to point you in the right direction if you have specific questions.

**Comment by lifepillar** [comment]
Ah thanks, that helps! I'll certainly contact you for further assistance if I encounter some stumbling blocks.
