### ISSUE TITLE
Twisted fails to install, what version is recommended?

### ISSUE THREAD

**Issue by Trevelsby** [aristotle-mdr/aristotle-metadata-registry#1332]
I am trying to install Aristotle Metadata Registry using the code from GitHub. The instructions I am following might be a bit old, they say to install Twisted after cffi (using pip). Installing Twisted breaks down with this error

[virt_env] [ty28392@mercado jun_attempt]$ pip install Twisted==18.4.0
Collecting Twisted==18.4.0
  Using cached https://files.pythonhosted.org/packages/12/2a/e9e4fb2e6b2f7a75577e0614926819a472934b0b85f205ba5d5d2add54d0/Twisted-18.4.0.tar.bz2
Requirement already satisfied: zope.interface>=4.4.2 in ./virt_env/lib/python3.6/site-packages (from Twisted==18.4.0) (4.6.0)
Requirement already satisfied: constantly>=15.1 in ./virt_env/lib/python3.6/site-packages (from Twisted==18.4.0) (15.1.0)
Requirement already satisfied: incremental>=16.10.1 in ./virt_env/lib/python3.6/site-packages (from Twisted==18.4.0) (17.5.0)
Requirement already satisfied: Automat>=0.3.0 in ./virt_env/lib/python3.6/site-packages (from Twisted==18.4.0) (0.7.0)
Requirement already satisfied: hyperlink>=17.1.1 in ./virt_env/lib/python3.6/site-packages (from Twisted==18.4.0) (19.0.0)
Requirement already satisfied: setuptools in ./virt_env/lib/python3.6/site-packages (from zope.interface>=4.4.2->Twisted==18.4.0) (40.6.2)
Requirement already satisfied: attrs>=16.1.0 in ./virt_env/lib/python3.6/site-packages (from Automat>=0.3.0->Twisted==18.4.0) (19.1.0)
Requirement already satisfied: six in ./virt_env/lib/python3.6/site-packages (from Automat>=0.3.0->Twisted==18.4.0) (1.12.0)
Requirement already satisfied: idna>=2.5 in ./virt_env/lib/python3.6/site-packages (from hyperlink>=17.1.1->Twisted==18.4.0) (2.8)
Installing collected packages: Twisted
  Running setup.py install for Twisted ... error
    ERROR: Complete output from command /home/wxfile/14/tr28892/Projects/jun_attempt/virt_env/bin/python3.6 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-k629uevf/Twisted/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-zg2s_6ck/install-record.txt --single-version-externally-managed --compile --install-headers /home/wxfile/14/tr28892/Projects/jun_attempt/virt_env/include/site/python3.6/Twisted:
    ERROR: running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/twisted
    copying src/twisted/_version.py -> build/lib.linux-x86_64-3.6/twisted
    copying src/twisted/__init__.py -> build/lib.linux-x86_64-3.6/twisted

... (cutting out a number of lines beginning with 'copying src/twisted...')

    writing top-level names to src/Twisted.egg-info/top_level.txt
    reading manifest file 'src/Twisted.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no previously-included files matching '*.misc' found under directory 'src/twisted'
    warning: no previously-included files matching '*.bugfix' found under directory 'src/twisted'
    warning: no previously-included files matching '*.doc' found under directory 'src/twisted'
    warning: no previously-included files matching '*.feature' found under directory 'src/twisted'
    warning: no previously-included files matching '*.removal' found under directory 'src/twisted'
    warning: no previously-included files matching 'NEWS' found under directory 'src/twisted'
    warning: no previously-included files matching 'README' found under directory 'src/twisted'
    warning: no previously-included files matching 'newsfragments' found under directory 'src/twisted'
    warning: no previously-included files found matching 'src/twisted/topfiles/CREDITS'
    warning: no previously-included files found matching 'src/twisted/topfiles/ChangeLog.Old'
    warning: no previously-included files found matching 'pyproject.toml'
    warning: no previously-included files found matching 'codecov.yml'
    warning: no previously-included files found matching 'appveyor.yml'
    warning: no previously-included files found matching '.circleci'
    warning: no previously-included files matching '*' found under directory '.circleci'
    no previously-included directories found matching 'bin'
    no previously-included directories found matching 'admin'
    no previously-included directories found matching '.travis'
    no previously-included directories found matching '.github'
    warning: no previously-included files found matching 'docs/historic/2003'
    warning: no previously-included files matching '*' found under directory 'docs/historic/2003'
    writing manifest file 'src/Twisted.egg-info/SOURCES.txt'
    copying src/twisted/test/cert.pem.no_trailing_newline -> build/lib.linux-x86_64-3.6/twisted/test
    copying src/twisted/test/key.pem.no_trailing_newline -> build/lib.linux-x86_64-3.6/twisted/test
    copying src/twisted/test/raiser.c -> build/lib.linux-x86_64-3.6/twisted/test
    copying src/twisted/test/raiser.pyx -> build/lib.linux-x86_64-3.6/twisted/test
    copying src/twisted/test/server.pem -> build/lib.linux-x86_64-3.6/twisted/test
    copying src/twisted/python/_sendmsg.c -> build/lib.linux-x86_64-3.6/twisted/python
    copying src/twisted/python/twisted-completion.zsh -> build/lib.linux-x86_64-3.6/twisted/python
    creating build/lib.linux-x86_64-3.6/twisted/python/_pydoctortemplates
    copying src/twisted/python/_pydoctortemplates/common.html -> build/lib.linux-x86_64-3.6/twisted/python/_pydoctortemplates
    copying src/twisted/python/_pydoctortemplates/index.html -> build/lib.linux-x86_64-3.6/twisted/python/_pydoctortemplates
    copying src/twisted/python/_pydoctortemplates/summary.html -> build/lib.linux-x86_64-3.6/twisted/python/_pydoctortemplates
    copying src/twisted/mail/test/rfc822.message -> build/lib.linux-x86_64-3.6/twisted/mail/test
    copying src/twisted/words/im/instancemessenger.glade -> build/lib.linux-x86_64-3.6/twisted/words/im
    copying src/twisted/words/xish/xpathparser.g -> build/lib.linux-x86_64-3.6/twisted/words/xish
    copying src/twisted/internet/iocpreactor/build.bat -> build/lib.linux-x86_64-3.6/twisted/internet/iocpreactor
    copying src/twisted/internet/iocpreactor/notes.txt -> build/lib.linux-x86_64-3.6/twisted/internet/iocpreactor
    creating build/lib.linux-x86_64-3.6/twisted/internet/iocpreactor/iocpsupport
    copying src/twisted/internet/iocpreactor/iocpsupport/acceptex.pxi -> build/lib.linux-x86_64-3.6/twisted/internet/iocpreactor/iocpsupport
    copying src/twisted/internet/iocpreactor/iocpsupport/connectex.pxi -> build/lib.linux-x86_64-3.6/twisted/internet/iocpreactor/iocpsupport
    copying src/twisted/internet/iocpreactor/iocpsupport/iocpsupport.c -> build/lib.linux-x86_64-3.6/twisted/internet/iocpreactor/iocpsupport
    copying src/twisted/internet/iocpreactor/iocpsupport/iocpsupport.pyx -> build/lib.linux-x86_64-3.6/twisted/internet/iocpreactor/iocpsupport
    copying src/twisted/internet/iocpreactor/iocpsupport/winsock_pointers.c -> build/lib.linux-x86_64-3.6/twisted/internet/iocpreactor/iocpsupport
    copying src/twisted/internet/iocpreactor/iocpsupport/winsock_pointers.h -> build/lib.linux-x86_64-3.6/twisted/internet/iocpreactor/iocpsupport
    copying src/twisted/internet/iocpreactor/iocpsupport/wsarecv.pxi -> build/lib.linux-x86_64-3.6/twisted/internet/iocpreactor/iocpsupport
    copying src/twisted/internet/iocpreactor/iocpsupport/wsasend.pxi -> build/lib.linux-x86_64-3.6/twisted/internet/iocpreactor/iocpsupport
    copying src/twisted/internet/test/_awaittests.py.3only -> build/lib.linux-x86_64-3.6/twisted/internet/test
    copying src/twisted/internet/test/_yieldfromtests.py.3only -> build/lib.linux-x86_64-3.6/twisted/internet/test
    creating build/lib.linux-x86_64-3.6/twisted/internet/test/fake_CAs
    copying src/twisted/internet/test/fake_CAs/chain.pem -> build/lib.linux-x86_64-3.6/twisted/internet/test/fake_CAs
    copying src/twisted/internet/test/fake_CAs/not-a-certificate -> build/lib.linux-x86_64-3.6/twisted/internet/test/fake_CAs
    copying src/twisted/internet/test/fake_CAs/thing1.pem -> build/lib.linux-x86_64-3.6/twisted/internet/test/fake_CAs
    copying src/twisted/internet/test/fake_CAs/thing2-duplicate.pem -> build/lib.linux-x86_64-3.6/twisted/internet/test/fake_CAs
    copying src/twisted/internet/test/fake_CAs/thing2.pem -> build/lib.linux-x86_64-3.6/twisted/internet/test/fake_CAs
    copying src/twisted/python/test/_deprecatetests.py.3only -> build/lib.linux-x86_64-3.6/twisted/python/test
    running build_ext
    building 'twisted.test.raiser' extension
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/src
    creating build/temp.linux-x86_64-3.6/src/twisted
    creating build/temp.linux-x86_64-3.6/src/twisted/test
    gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/home/wxfile/14/tr28892/Projects/jun_attempt/virt_env/include -I/usr/include/python3.6m -c src/twisted/test/raiser.c -o build/temp.linux-x86_64-3.6/src/twisted/test/raiser.o
    src/twisted/test/raiser.c:4:20: fatal error: Python.h: No such file or directory
     #include "Python.h"
                        ^
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command "/home/wxfile/14/tr28892/Projects/jun_attempt/virt_env/bin/python3.6 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-k629uevf/Twisted/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-zg2s_6ck/install-record.txt --single-version-externally-managed --compile --install-headers /home/wxfile/14/tr28892/Projects/jun_attempt/virt_env/include/site/python3.6/Twisted" failed with error code 1 in /tmp/pip-install-k629uevf/Twisted/

Thoughts? I tried installing Twisted without specifying a version (pip install Twisted) and got pretty much the same error. Is Twisted still a requirement to install Aristotle software? Is there a specific version of Twisted that should be used? It looks like they're up to 19.2.1 now. 

Thanks!

**Comment by LegoStormtroopr** [comment]
> The instructions I am following might be a bit old, they say to install Twisted after cffi (using pip). Installing Twisted breaks down with this error

I don't recall twisted ever being an explicit requirement, can you point out where this is listed in the instructions?

**Comment by Trevelsby** [comment]
Thanks, you're right. Twisted was not required, I was able to complete the installation without it. 

I guess I was using an old version of the instructions, I'm not able to locate it on GitHub anymore. Thanks for the help, my version is up and running

**Comment by LegoStormtroopr** [comment]
@Trevelsby if you can email me, I'd be interested to hear about how you are using the platform and needs for a metadata registry.
