### ISSUE TITLE
Static Resources and Media fail to load when switching over to Production

### ISSUE THREAD

**Issue by Trevelsby** [aristotle-mdr/aristotle-metadata-registry#1418]
Hi folks, I am trying to set up Aristotle as if it were in production and running into some issues. Overall I was curious if other parties have been able to set up Aristotle and run it in a production environment, with DEBUG=False? I'm trying to do that myself and in my case Aristotle can't find the STATIC and MEDIA resources once DEBUG is set to False. I do understand that Django does not serve the files once DEBUG is false, I am using the method to serve the static files from a separate dedicated server (httpd - Apache). I'm following directions from this page

https://docs.djangoproject.com/en/2.2/howto/static-files/deployment/

In terms of the exact steps, this page illustrates them clearly

https://help.pythonanywhere.com/pages/DjangoStaticFiles/

So yeah, I reconfigured STATIC_ROOT and MEDIA_ROOT in settings.py to point to folders inside my httpd directory (making the files available from the Apache service). Then I ran manage.py collectstatic, and that worked, all the static files were copied into the new directories I had set up. At this point the final step (as far as I can tell) was to set DEBUG = False and reload the page. I did this and none of the CSS or JS files were retrieved, the page was messy, raw HTML with no styling (and completely unusable). Checking the runserver output there were errors for failing to retrieve the web resources

Loading failed for the <script> with source “http://localhost:8000/static/aristotle_mdr/bootstrap/js/bootstrap.min.js”.
Loading failed for the <script> with source “http://localhost:8000/static/aristotle_mdr/aristotle.js”.
Loading failed for the <script> with source “http://localhost:8000/static/bootstrap3_datetime/moment.min.js”.
Loading failed for the <script> with source “http://localhost:8000/static/bootstrap3_datetime/bootstrap-datetimepicker.min.js”.

I switched DEBUG back to True and tried to access the specific JS files at the URLs stated, they are all there in the correct location. But when DEBUG is False they are unreachable...I don't get it. 

I understand if connecting with another server is out of your project's scope, but do you know for sure that others have gotten this to work in production with DEBUG=False? I think I've followed all the right steps and have discussed with colleagues that have Django experience but unable to make it happen. Any thoughts or suggestions from the Aristotle developers?

Thanks!
Trevelsby

**Comment by LegoStormtroopr** [comment]
Generally, your media and static files are going to be served through the web server you have setup in front of your django application.

We don't use Apache for our commercially supported production installations, so we can't provide too much information on your current setup. What I can say is that if the files aren't being served you may need to have apache setup to load files from the STATIC_ROOT.

We do provide dockerised instances that can be much easier for users to self-manage. If you want more information on this, feel free to email me and we can discuss your project needs.

**Comment by Trevelsby** [comment]
Sorry for the delay, was able to get things working with more Django research. Thanks for the pointers!
