### ISSUE TITLE
description needs to be renamed definition

### ISSUE THREAD

**Issue by LegoStormtroopr** [aristotle-mdr/aristotle-metadata-registry#148]
`baseAristotleObject.description` should really be defined internally as `.definition` to map with 11179 as description is used elsewhere (specifically as a description on Value Domains)

The errant lines are in `models.py` at these locations:
* https://github.com/aristotle-mdr/aristotle-metadata-registry/blob/master/aristotle_mdr/models.py#L45
* https://github.com/aristotle-mdr/aristotle-metadata-registry/blob/master/aristotle_mdr/models.py#L655

However, changes would need to take place across many of the views and templates as well.

**Comment by dylan-kerr** [comment]
I've started looking at this. Who can resist a t-shirt?

**Comment by LegoStormtroopr** [comment]
:+1: Let me know if you need any help

**Comment by LegoStormtroopr** [comment]
This was closed by #217
