### ISSUE TITLE
Can't download PDF

### ISSUE THREAD

**Issue by Rknowles0** [aristotle-mdr/aristotle-metadata-registry#1490]
On item view page, in this case a Data Element.
click Download -> PDF
Download Options page. Made no selections or changes.
click Download
Preparing Download page first says "Preparing" than has error. See image:

![image](https://user-images.githubusercontent.com/50208856/63966708-d8409a00-ca69-11e9-8666-24ba104c5e87.png)

[no-pdf-ps.txt](https://github.com/aristotle-mdr/aristotle-metadata-registry/files/3556915/no-pdf-ps.txt)

[no-pdf-logs.txt](https://github.com/aristotle-mdr/aristotle-metadata-registry/files/3556917/no-pdf-logs.txt)

**Comment by LegoStormtroopr** [comment]
Hi @Rknowles0, based on the docker logs it looks like the worker process isn't booting correctly. This is used to asynchronously create the downloaded files.

**Comment by Rknowles0** [comment]
I am running multiple instances of Aristotle, though never at the same time on one host. On one machine I run with our main database and a second instance with a small test database. The original error was on the main DB. I switched instances to get a worker log, but instead found that PDF Download worked on my test DB instance. It still fails on the main DB. I'd say this looks like some difference in my two configurations.

As for worker process trouble, the worker log at startup looks the same on both instances, and there is nothing else logged after I try the download on either instance. I'll be looking more closely at configuration, but here's the log in case it tells you anything (for me to fix!)

`$ docker-compose logs worker
Attaching to clienttwo_worker_1
worker_1         | System check identified some issues:
worker_1         | 
worker_1         | WARNINGS:
worker_1         | ?: (urls.W002) Your URL pattern '^/?$' [name='glossary'] has a regex beginning with a '/'. Remove this slash as it is unnecessary. If this pattern is targeted in an include(), ensure the include() pattern has a trailing '/'.
worker_1         | ?: (urls.W002) Your URL pattern '^/?$' has a regex beginning with a '/'. Remove this slash as it is unnecessary. If this pattern is targeted in an include(), ensure the include() pattern has a trailing '/'.
worker_1         | ?: (urls.W002) Your URL pattern '^/?$' has a regex beginning with a '/'. Remove this slash as it is unnecessary. If this pattern is targeted in an include(), ensure the include() pattern has a trailing '/'.
worker_1         | ?: (urls.W005) URL namespace 'api_v4' isn't unique. You may not be able to reverse all URLs in this namespace
worker_1         | ?: (urls.W005) URL namespace 'api_v4:issues' isn't unique. You may not be able to reverse all URLs in this namespace
worker_1         | ?: (urls.W005) URL namespace 'api_v4:item' isn't unique. You may not be able to reverse all URLs in this namespace
worker_1         | ?: (urls.W005) URL namespace 'api_v4:reviews' isn't unique. You may not be able to reverse all URLs in this namespace
worker_1         | ?: (urls.W005) URL namespace 'aristotle_mdr_api.v3' isn't unique. You may not be able to reverse all URLs in this namespace
worker_1         | ?: (urls.W005) URL namespace 'aristotle_mdr_api.v3:api-docs' isn't unique. You may not be able to reverse all URLs in this namespace
worker_1         | ?: (urls.W005) URL namespace 'aristotle_mdr_api.v3:aristotle_mdr_api.v3' isn't unique. You may not be able to reverse all URLs in this namespace
worker_1         | ?: (urls.W005) URL namespace 'aristotle_mdr_links' isn't unique. You may not be able to reverse all URLs in this namespace
worker_1         | ?: (urls.W005) URL namespace 'rest_framework' isn't unique. You may not be able to reverse all URLs in this namespace
worker_1         | ?: (urls.W005) URL namespace 'token_auth' isn't unique. You may not be able to reverse all URLs in this namespace
worker_1         | aristotle_glossary.GlossaryItem.index: (fields.W340) null has no effect on ManyToManyField.
worker_1         | aristotle_mdr_validators.RAValidationRules.registration_authority: (fields.W342) Setting unique=True on a ForeignKey has the same effect as using a OneToOneField.
worker_1         | 	HINT: ForeignKey(unique=True) is usually better served by a OneToOneField.
worker_1         | 
worker_1         | System check identified 15 issues (3 silenced).
`

**Comment by Rknowles0** [comment]
I tested latest docker images and config today. Both web and worker are running as non-root. However, when I try a PDF download nothing is actually written to the media volume. Logs for the download:
```
web_1            | /media/1/25d70ada5ad3ee1aaa1fab27eedd671b381e861146e2712edc862c486f8e6cea/download.pdf
worker_1 <Nothing>
nginx_1          | 2019/10/10 21:12:48 [error] 9#9: *18 open() "/app/media/1/25d70ada5ad3ee1aaa1fab27eedd671b381e861146e2712edc862c486f8e6cea/download.pdf" failed (2: No such file or directory), client: 155.34.142.88, server: , request: "GET /media/1/25d70ada5ad3ee1aaa1fab27eedd671b381e861146e2712edc862c486f8e6cea/download.pdf HTTP/1.1", host: "gertrude", referrer: "http://gertrude/download/pdf/7"
nginx_1          | 155.34.142.88 - - [10/Oct/2019:21:12:48 +0000] "GET /media/1/25d70ada5ad3ee1aaa1fab27eedd671b381e861146e2712edc862c486f8e6cea/download.pdf HTTP/1.1" 404 146 "http://gertrude/download/pdf/7" "Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0"
```
When I go to a shell in nginx, there's nothing in media:
```
/ # ls -alt /app/media/1
total 8
drwxr-xr-x    2 1000     1000          4096 Oct 10 21:11 .
drwxrwxrwx    4 1000     1000          4096 Oct 10 21:11 ..
```
Owner, group, and permissions may be off because I tried playing with them so that web or worker would be able to write the pdf file. Any advice on how I should set or reset /app/media?

**Comment by Rknowles0** [comment]
Still no PDF files with aristotle_mdr-nginx:3.0.3 and aristotle_mdr-django:3.0.3. No pdf when I run web and worker as root or as the default "user:www". I browsed to an item then the log below occurs for the steps "Download -> PDF"; "Download Options" page -> "Download"; "<Item> Download" page -> "Download now"; "404 Not Found".

```
nginx_1          | 155.34.142.88 - - [13/Nov/2019:21:45:13 +0000] "GET /download/options/pdf?items=3 HTTP/1.1" 200 18426 "http://gertrude/item/3/property/quality" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
nginx_1          | 155.34.142.88 - - [13/Nov/2019:21:45:13 +0000] "GET /user/1/profilePicture.svg HTTP/1.1" 200 1765 "http://gertrude/download/options/pdf?items=3" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
nginx_1          | 155.34.142.88 - - [13/Nov/2019:21:45:17 +0000] "POST /download/options/pdf?items=3 HTTP/1.1" 302 0 "http://gertrude/download/options/pdf?items=3" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
nginx_1          | 155.34.142.88 - - [13/Nov/2019:21:45:17 +0000] "GET /download/pdf/3 HTTP/1.1" 200 15290 "http://gertrude/download/options/pdf?items=3" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
nginx_1          | 155.34.142.88 - - [13/Nov/2019:21:45:17 +0000] "GET /user/1/profilePicture.svg HTTP/1.1" 200 1765 "http://gertrude/download/pdf/3" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
web_1            | /media/1/8be9f7f411ffa54d5876816a7d6147114538712ee29ac9050b5cf094827592c1/download.pdf
nginx_1          | 155.34.142.88 - - [13/Nov/2019:21:45:18 +0000] "GET /dlstatus/a48b931d-84f8-4cd0-8db8-071c5882a85b HTTP/1.1" 200 179 "http://gertrude/download/pdf/3" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
nginx_1          | 2019/11/13 21:45:22 [error] 9#9: *43 open() "/app/media/1/8be9f7f411ffa54d5876816a7d6147114538712ee29ac9050b5cf094827592c1/download.pdf" failed (2: No such file or directory), client: 155.34.142.88, server: , request: "GET /media/1/8be9f7f411ffa54d5876816a7d6147114538712ee29ac9050b5cf094827592c1/download.pdf HTTP/1.1", host: "gertrude", referrer: "http://gertrude/download/pdf/3"
nginx_1          | 155.34.142.88 - - [13/Nov/2019:21:45:22 +0000] "GET /media/1/8be9f7f411ffa54d5876816a7d6147114538712ee29ac9050b5cf094827592c1/download.pdf HTTP/1.1" 404 146 "http://gertrude/download/pdf/3" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
```

**Comment by Rknowles0** [comment]
Still no PDF files with aristotle_mdr-nginx:3.0.4 and aristotle_mdr-django:3.0.4. Error is the same as with 3.0.3.

One further discovery: Worker does write the pdf file, but it writes it to its /home/user/media/1 directory. The media directory shared by  web, worker, and nginx is /app/media. So worker creates and writes a file, but nginx cannot access that file and expects it in another place.

**Comment by harrywhite4** [comment]
This should be fixed in the latest release

**Comment by Rknowles0** [comment]
I'm now running 3.0.9 and PDF is working. Thanks you.
