### ISSUE TITLE
Default role when adding users to workgroup shouldn't be 'manager'

### ISSUE THREAD

**Issue by LegoStormtroopr** [aristotle-mdr/aristotle-metadata-registry#1517]
![image](https://user-images.githubusercontent.com/2173174/65732263-61e89380-e10c-11e9-9f4d-450ce0059955.png)

**Comment by fragalcer** [comment]
What should be the default value? Is it supposed to have a "blank" value in the dropdown?

**Comment by LegoStormtroopr** [comment]
I've got a fix for this in the attached PR. So its all taken care of.
