### ISSUE TITLE
Workgroup links not available to non-superusers. Permissions not applied to edit buttons

### ISSUE THREAD

**Issue by LegoStormtroopr** [aristotle-mdr/aristotle-metadata-registry#1529]
![image](https://user-images.githubusercontent.com/2173174/67261022-607f7080-f4ea-11e9-9a0a-092c16ab5b8d.png)

* Workgroup name is not clickable
* Edit button always shows (page behind button still has permissions applied)

**Comment by s-i-l-k-e** [comment]
![image](https://user-images.githubusercontent.com/38807135/68167340-44cf9c00-ffb9-11e9-9cd4-0f5a315f9c04.png)
For a superuser
![image](https://user-images.githubusercontent.com/38807135/68167446-9d069e00-ffb9-11e9-9f0b-df24fc1d3657.png)
For a regular user with viewing permissions for the workgroup
