### ISSUE TITLE
Add support for Django 1.9/1.10

### ISSUE THREAD

**Issue by LegoStormtroopr** [aristotle-mdr/aristotle-metadata-registry#159]
There are already a few deprecation warnings in the test suite, so getting on top of these early would be handy.

Libraries that may/may not require updates
* [ ] Haystack 
* [ ] Bootstrap3-Datepicker (this requires a complete library change to Bootstrap3-Datepicker2 with new static files)

**Comment by LegoStormtroopr** [comment]
There are a bunch of libraries with sketchy support for 1.9, so this may be a long process.

**Comment by LegoStormtroopr** [comment]
Still waiting on Haystack - https://github.com/django-haystack/django-haystack/issues/1282

**Comment by jkaluzka** [comment]
@LegoStormtroopr can I work on that?

**Comment by LegoStormtroopr** [comment]
By all means :D

**Comment by LegoStormtroopr** [comment]
Done!
