### ISSUE TITLE
Footer spacing on IE

### ISSUE THREAD

**Issue by LegoStormtroopr** [aristotle-mdr/aristotle-metadata-registry#1731]
On all other browsers the sidebar and footer extend to bottom of the page but this not the case on IE11

Firefox:
![image](https://user-images.githubusercontent.com/12134063/70297402-03454180-1842-11ea-9b91-d9f0453f373c.png)

IE11:
![Screenshot from 2019-12-06 16-04-11_cropped](https://user-images.githubusercontent.com/12134063/70297459-3ee00b80-1842-11ea-976e-82e8df2063e7.png)

**Comment by s-i-l-k-e** [comment]
@LegoStormtroopr thanks for reporting. This has been fixed.
