### ISSUE TITLE
Strange rendering of "Unlocked" section in registrationauthority view

### ISSUE THREAD

**Issue by borsna** [aristotle-mdr/aristotle-metadata-registry#195]
![image](https://cloud.githubusercontent.com/assets/794445/7897977/666d377a-06f1-11e5-94ab-a6dc4f2cebcb.png)
From http://aristotle.pythonanywhere.com/registrationauthority/9

**Comment by LegoStormtroopr** [comment]
Removed sidebar and improved CSS

![image](https://cloud.githubusercontent.com/assets/2173174/8010040/4924f794-0bf0-11e5-8193-b213f26ef635.png)
