### ISSUE TITLE
Handling of html in description

### ISSUE THREAD

**Issue by borsna** [aristotle-mdr/aristotle-metadata-registry#196]
On http://aristotle.pythonanywhere.com/item/436861/indicator/national-healthcare-agreement-pi-67-capital-expend

html tag <p> is visible, unsure if this is from the database or an escaping in the output template
```
Disaggreation
<P>2007–08 and 2008–09 (updated as necessary for revised total health expenditure estimates), and 2009–10—State and territory (numerator/denominator/ratio) </P>
```

**Comment by LegoStormtroopr** [comment]
Thats content that has been entered by a person and comes from the database, so its not easy to fix.
