### ISSUE TITLE
Use ISO 8601 dates as default

### ISSUE THREAD

**Issue by borsna** [aristotle-mdr/aristotle-metadata-registry#198]
Current form:
``April 16, 2015``
Only sane format:
``2015-04-16``
![iso_8601](https://cloud.githubusercontent.com/assets/794445/7898010/e5de9516-06f2-11e5-84aa-efd703ce7c43.png)

Example in sidebar on http://aristotle.pythonanywhere.com/item/602811/objectclass/person

**Comment by LegoStormtroopr** [comment]
I've reverted to ISO dates in the info box, but there are bound to be a few more spots where this is an issue. Non-ISO dates in the infobox can be overridden by adding a local template at ``templates/aristotle_mdr/concepts/infobox.html``
