### ISSUE TITLE
Ready to review flag

### ISSUE THREAD

**Issue by jadedjester** [aristotle-mdr/aristotle-metadata-registry#20]
I can see your intention with the ready to review flag - however in 11179 the registration statuses act as the flag for registrar review. e.g. the data developer marking item as Proposed signals to the registrar this item is ready for review. 

When this flag is used who is notified and how? If the item is not associated with a (RA) workflow the system wouldn't know which registrar to notify (assuming multiple registrars, for multiple registration authorities of course). 

I'd recommend removing unless you have a specific purpose in mind...such as...??

**Comment by LegoStormtroopr** [comment]
I've added a few more columns for this. It will be useful to keep an eye on this issue as Aristotle is adopted, but once the changes are in, I'll close this bug for now.
