### ISSUE TITLE
Spelling mistakes for notifications

### ISSUE THREAD

**Issue by jfihn** [aristotle-mdr/aristotle-metadata-registry#200]
Someone motified item in workgroup
Someone new item in workgroup

![image](https://cloud.githubusercontent.com/assets/3796730/7898037/b4dc60be-06f3-11e5-9dc6-f36c1c771933.png)

**Comment by LegoStormtroopr** [comment]
A better multilingual approach to this needs to be made as translation is done at the time the notification is made, and not translated per user.
