### ISSUE TITLE
Recent action created without any object being changed?

### ISSUE THREAD

**Issue by jfihn** [aristotle-mdr/aristotle-metadata-registry#203]
![image](https://cloud.githubusercontent.com/assets/3796730/7898125/5674557e-06f6-11e5-9b38-012a16c1e614.png)

**Comment by LegoStormtroopr** [comment]
![image](https://cloud.githubusercontent.com/assets/2173174/8010267/3126d0d4-0bf2-11e5-806f-56d5fff5a472.png)
