### ISSUE TITLE
Add support for Python 3

### ISSUE THREAD

**Issue by LegoStormtroopr** [aristotle-mdr/aristotle-metadata-registry#211]
This has begun in #188 but there is still a fair bit of work to-do.

**Comment by LegoStormtroopr** [comment]
Looks like py xhtml2pdf is now python3 compatible! https://pypi.python.org/pypi/xhtml2pdf

**Comment by LegoStormtroopr** [comment]
This needs to be completed by 2020 - http://pythonclock.org/

**Comment by souravsingh** [comment]
I can work on the issue

**Comment by LegoStormtroopr** [comment]
This is about to be closed in #563 !
