### ISSUE TITLE
Aristotle is called a metadata registry but the logo image is using "MetaData Repository"

### ISSUE THREAD

**Issue by borsna** [aristotle-mdr/aristotle-metadata-registry#234]
![MetaData Repository](http://aristotle.pythonanywhere.com/static/aristotle_mdr/images/aristotle_small.png)

I suggest replacing Repository in the logo image and use Registry in all places (less confusion).

**Comment by borsna** [comment]
Checked my t-shiirt. It uses the same image but the correct text "Aristotle MetaData Registry" (no need to file a t-shirt bug).

**Comment by LegoStormtroopr** [comment]
> Checked my t-shiirt. It uses the same image but the correct text "Aristotle MetaData Registry" (no need to file a t-shirt bug).

ಠ_ಠ

(╯°□°）╯︵ ┻━┻

**Comment by borsna** [comment]
![31mamjwttdl](https://cloud.githubusercontent.com/assets/794445/11062742/bae235bc-87b1-11e5-8b96-296f1eb46959.jpg)
