### ISSUE TITLE
Edit screen inconsistent use of camel casing

### ISSUE THREAD

**Issue by jadedjester** [aristotle-mdr/aristotle-metadata-registry#26]
Camel casing is not used consistently in edit screen. E.g. Registration Authority is the only label not camel cased in the Statuses block:
http://aristotle.pythonanywhere.com/admin/aristotle_mdr/valuedomain/44/

Suggest using plain text instead for all labels. I'm assuming not everyone using this screen will be IT minded and this may be confusing to use.

**Comment by LegoStormtroopr** [comment]
This would probably be better solved through translated labels on the fields.
