### ISSUE TITLE
Crash when trying to view objects

### ISSUE THREAD

**Issue by jfihn** [aristotle-mdr/aristotle-metadata-registry#325]
http://aristotle.pythonanywhere.com/browse/268985/269604-area-of-clinical-practice
http://aristotle.pythonanywhere.com/browse/268985/269605-principal-role
etc.

**Comment by LegoStormtroopr** [comment]
Current investigating this. Seems to just be an issue in the templates, but I'll write some tests to cover it and release a v1.1.1 in the next week or so.
