### ISSUE TITLE
Objectclass creation wizard errors with non-unique workgroups 

### ISSUE THREAD

**Issue by thsutton** [aristotle-mdr/aristotle-metadata-registry#333]
The creation wizards on the test server (for both object classes and value domains) error out for me with an exception: `get() returned more than one Workgroup -- it returned 3!`

The HTML of the workgroup field is:

````
<select id="id_results-workgroup" name="results-workgroup">
<option value="">---------</option>
<option value="4" selected="selected">Demonstration Workgroup</option>
<option value="4">Demonstration Workgroup</option>
<option value="4">Demonstration Workgroup</option>
</select>
````

I assume there's a problem either in the database being run on the test server?

**Comment by LegoStormtroopr** [comment]
Is this on aristotle.pythonanywhere.com ?

**Comment by thsutton** [comment]
Yes.

**Comment by LegoStormtroopr** [comment]
I've checked the admin pages and there is only one workgroup with that name. Which user are you logged in as, and what name/definition did you use on step 1?

**Comment by thsutton** [comment]
I'm logged in with demo_editor:demo_editor and I can only see a single workgroup in the user dashboard. On step one I've used name: Account, version: 1, description: "An account". Also just keyboard mashing.

Both wizards search and present the step 2 form but then the Next button displays the same exception.

**Comment by LegoStormtroopr** [comment]
Aha! Good find, the error is on either of these lines here:

* https://github.com/aristotle-mdr/aristotle-metadata-registry/blob/v1.1.1/aristotle_mdr/models.py#L1232
* https://github.com/aristotle-mdr/aristotle-metadata-registry/blob/v1.1.1/aristotle_mdr/forms/creation_wizards.py#L186

Either way, it looks like `editable_workgroups` can return duplicate workgroups based on a users role (if they have duplicate roles in a workgroup), this causes the field to have duplicates, which django throws an error on.

I've linked to the v1.1.1 dev-branch, so it should be safe to branch of that, fix, add tests, and roll into v1.1.1 sometime later this week as it will close a few tricky bugs.

**Comment by LegoStormtroopr** [comment]
@thsutton did you want to tackle this one? Apart from branch management and a new test to check for this in the future, this should be very straight forward.

**Comment by thsutton** [comment]
@LegoStormtroopr Sure. I'm evaluating it for potential use at work so I'll run into this pretty soon. I'll try and get something opened later today or tomorrow (depending on how quickly I can get an instance stood up locally)

**Comment by LegoStormtroopr** [comment]
Thanks for the help! Glad to hear you are checking it out.
