### ISSUE TITLE
Sample data has missing required fields

### ISSUE THREAD

**Issue by thsutton** [aristotle-mdr/aristotle-metadata-registry#336]
Some of the sample objects created in a default install are missing required fields. For example the sample Workgroups -- "Possum Workgroup", "System Workgroup", "ISO/IEC Workgroup" -- are all missing their "definition" field.

**Comment by thsutton** [comment]
I haven't looked at the standard but it might be appropriate to add the quantities corresponding to the other three SI base units in the sample data?

**Comment by LegoStormtroopr** [comment]
Ideally, these should all be pulled out into [django fixture files](https://docs.djangoproject.com/en/1.8/howto/initial-data/) and loaded properly.

The interim fix is adding definitions in the `default_data` method, the better fix is migrating those into fixtures - this means that "ISO standards" (and potentially other widely used metadata) can then be packaged as downloadable files.
