### ISSUE TITLE
Redirect loop when attempting to creating object as demo_registrar 

### ISSUE THREAD

**Issue by thsutton** [aristotle-mdr/aristotle-metadata-registry#338]
Logging in to the pythonanywhere.com site as `demo_registrar` and clicking, e.g., "+" -> "Object class" links to http://aristotle.pythonanywhere.com/create/aristotle_mdr/objectclass which then enters into a redirect loop with http://aristotle.pythonanywhere.com/login?next=create/aristotle_mdr/objectclass

**Comment by LegoStormtroopr** [comment]
This is a pretty basic one as well.

[On this line, there is a class based in `views/wizards.py`](https://github.com/aristotle-mdr/aristotle-metadata-registry/blob/develop/aristotle_mdr/views/wizards.py#L61)

    @method_decorator(permission_required('aristotle_mdr.user_is_editor'))
    def dispatch(self, *args, **kwargs):
        return super(PermissionWizard, self).dispatch(*args, **kwargs)

The decorator checks for the permission, and if it fails, redirects to a login. Which is fine, except if the user is logged in.

Instead the decorator permission check should be just if the user is logged in, and then if they aren't an editor [`raise Http404` as shown on this line in the same file.](https://github.com/aristotle-mdr/aristotle-metadata-registry/blob/develop/aristotle_mdr/views/wizards.py#L42)
