### ISSUE TITLE
Wrong padding for facets on search page

### ISSUE THREAD

**Issue by borsna** [aristotle-mdr/aristotle-metadata-registry#358]
Added a fix in: https://github.com/aristotle-mdr/aristotle-metadata-registry/compare/develop...borsna:patch-7

Before:
![image](https://cloud.githubusercontent.com/assets/794445/13555262/ecf718cc-e3bb-11e5-986f-10608c2db3fe.png)

After:
![image](https://cloud.githubusercontent.com/assets/794445/13555256/c93e477a-e3bb-11e5-8488-4fc0609a9cdd.png)

**Comment by LegoStormtroopr** [comment]
Closed in PR #359
