### ISSUE TITLE
Need URL field for primary reference for indicator

### ISSUE THREAD

**Issue by gilliankerr** [aristotle-mdr/aristotle-metadata-registry#422]
Each indicator should have a field for 'Reference' that allows an URL. This field would contain the hyperlink for the primary citation or reference for the indicator. It is the same as the DHIS2 URL field.

**Comment by LegoStormtroopr** [comment]
All `concept` objects (including Indicators) have a references field that allows for a rich text component. Is this enough?

**Comment by gilliankerr** [comment]
hi, Sam – Yes, the reference field with rich text is enough. We may need another solution later depending on the DHIS2 structure, but it’s low priority.
