### ISSUE TITLE
Dashboard feature

### ISSUE THREAD

**Issue by jadedjester** [aristotle-mdr/aristotle-metadata-registry#46]
Displays recently created items, but doesn’t provide detailed information. Suggest displaying detailed information here i.e. Registration status/RA, last edited author/date, date created, object type. Alternatively provide a link to the Polls screen for the workgroup and display more detailed information in that view. Thoughts?

**Comment by LegoStormtroopr** [comment]
Can you give some more details on what you want on this page? Maybe some mockups?

**Comment by LegoStormtroopr** [comment]
Closing as this can be done through an extension.
