### ISSUE TITLE
Easy installer attempts to download directory that doesn't exist

### ISSUE THREAD

**Issue by thsutton** [aristotle-mdr/aristotle-metadata-registry#479]
Running the easy installed as described (`python -m aristotle_mdr.install.easy`) results in a failure when SVN can't export a directory which doesn't exist:

````
svn: E170000: URL 'https://github.com/aristotle-mdr/aristotle-metadata-registry/trunk/example_mdr' doesn't exist
````

**Comment by thsutton** [comment]
I hacked the `.install.easy` module to include `aristotle_mdr/install/` in the SVN path and that worked.

**Comment by LegoStormtroopr** [comment]
Cheers. With Aristotle now on PyPI it should be possible to do an easy install along the lines of:

```
pip install aristotle-metadata-registry
easy_install_aristotle.py
```

Or something, I'll get this fixed soon (or if you have suggestions, fire away).
Thanks.
