### ISSUE TITLE
Possible tip/FAQ about LESS compilation

### ISSUE THREAD

**Issue by thsutton** [aristotle-mdr/aristotle-metadata-registry#480]
A fresh easy start install of mine with the node-based LESS compiler installed globally resulted in errors due to some node thing or other.

Installing `lesscpy` in the virtualenv and symlinking it as `$VENV/bin/lessc` made the site work. I assume there's also a way to tell the Django app that does the compiling to use the other command.

This would make a good tip or FAQ. If I get around to it I'll open a PR against the docs.

**Comment by LegoStormtroopr** [comment]
I think a better solution is just compiling the LESS to CSS and removing that as a requirement all together.
The CSS isn't that complex and can be cleaned up as part of the process.

**Comment by LegoStormtroopr** [comment]
Thanks for the heads up, I've added lesscpy as a requirement in `setup.py`, and should be able to replace npm/less as a requirement.

**Comment by LegoStormtroopr** [comment]
Nope, waiting on lessc changes to be included upstream - docs to be improved.
