### ISSUE TITLE
Published/registered items show in "Sandbox"

### ISSUE THREAD

**Issue by LegoStormtroopr** [aristotle-mdr/aristotle-metadata-registry#500]
This can be fixed by altering the queryset code in [user pages](https://github.com/aristotle-mdr/aristotle-metadata-registry/blob/develop/aristotle_mdr/views/user_pages.py#L267) and just needs an additional test case in [user tests](https://github.com/aristotle-mdr/aristotle-metadata-registry/blob/develop/aristotle_mdr/tests/main/test_user_pages.py).

Highlighted item should not be in this listing.

![image](https://cloud.githubusercontent.com/assets/2173174/18980187/2a14cbda-8715-11e6-81b5-a916321df43c.png)

**Comment by mtham8** [comment]
Hi, for clarification, the highlighted should not be shown because it is registered right?

**Comment by LegoStormtroopr** [comment]
@mtham8 Thats correct - only its which aren't registered or published should be shown on this screen.

**Comment by LegoStormtroopr** [comment]
Closed in #501! Thanks #hacktoberfest

@mtham8 If you are doing #hacktoberfest, I'd be happy to help you with another bug?
