### ISSUE TITLE
Rename allRegistrationAuthority URLs

### ISSUE THREAD

**Issue by LegoStormtroopr** [aristotle-mdr/aristotle-metadata-registry#509]
These urls: `allRegistrationAuthorities` need to be converted to underscore case.

**Comment by jdibiccari** [comment]
I'd like to grab this one if I may!

**Comment by ryanwake** [comment]
I'll get on this.

**Comment by drgarcia1986** [comment]
PR #512 is open :smile:

**Comment by ryanwake** [comment]
PR #513

**Comment by LegoStormtroopr** [comment]
Thanks for your help @ryanwake and @drgarcia1986 !

**Comment by drgarcia1986** [comment]
you're welcome !
