### ISSUE TITLE
Browse pages shouldn't show metadata items as an option when there are zero

### ISSUE THREAD

**Issue by LegoStormtroopr** [aristotle-mdr/aristotle-metadata-registry#527]
The rows wth zero entries below shouldn't be visible.

Check the `aristotle_mdr.contrib.browse` module for code for this:

![image](https://cloud.githubusercontent.com/assets/2173174/19583767/293d3126-978b-11e6-94ae-e83a972e630d.png)

**Comment by sounak98** [comment]
I'll take this up.

**Comment by LegoStormtroopr** [comment]
Closed in #579
