### ISSUE TITLE
Need a custom 500 page

### ISSUE THREAD

**Issue by LegoStormtroopr** [aristotle-mdr/aristotle-metadata-registry#529]
A nice error page instead of the very plain one would be good for usability.

Needs to accurately recognise the user is logged in.

**Comment by polaroi8d** [comment]
Hey, I will try it if, nobody working on this. Hmmm?

**Comment by LegoStormtroopr** [comment]
Absolutely. Nobody is working on it yet that I know.

**Comment by itepifanio** [comment]
This issue still open? I'm interested

**Comment by LegoStormtroopr** [comment]
No action came from it, so be my guest.

If you can have it inherit from (or look similar to) `base.html` so there is a consistent theme, that'd be great :)
