### ISSUE TITLE
Please explain.... how to create and revise slots

### ISSUE THREAD

**Issue by gilliankerr** [aristotle-mdr/aristotle-metadata-registry#546]
- I can create a new tag in an existing slot but can't create a new slot (e.g., Ratings)
- I want to change capitalizations on a couple of slots to make them consistent (e.g., Theory of change, not Theory of Change)

**Comment by LegoStormtroopr** [comment]
Update: These videos have been created and are currently being edited by @larrn

**Comment by LegoStormtroopr** [comment]
There is a new [repository for our knowledge base](https://github.com/aristotle-mdr/user-documentation), and this topic is now available at the following url:

http://help.aristotlemetadata.com/creating_and_editing/adding_new_info_with_slots.html
