### ISSUE TITLE
Bulk action to assign slot values

### ISSUE THREAD

**Issue by LegoStormtroopr** [aristotle-mdr/aristotle-metadata-registry#547]
Client request: be able to assign the same values to a slot to multiple items.

This would be a bulk action in aristotle_mdr.contrib.slots`

**Comment by thotarevanth** [comment]
@LegoStormtroopr  can you assign me this issue and help me in fixing this issue with some quick explanation with what to do?

**Comment by LegoStormtroopr** [comment]
Hey @thotarevanth,

I can't assign you as you aren't a member of the organization. But you can have a go at this. I've added some notes below:

The important code to review is in these sections:

* https://github.com/aristotle-mdr/aristotle-metadata-registry/blob/develop/aristotle_mdr/forms/bulk_actions.py:
* https://github.com/aristotle-mdr/aristotle-metadata-registry/tree/develop/aristotle_mdr/contrib/slots

In the `contrib.slots` module you'll need code like:
```
class BulkAssignSlotsForm(LoggedInBulkActionForm):
    classes="fa-bookmark"  # An appropriate font awesome icon (maybe tags?)
    action_text = _('Bulk add slots')
    items_label = "Add slot details to multiple metadata items"
    confirm_page = "aristotle_mdr/slots/bulk_actions/add_slots.html" # <- this file needs to be made

    slot=forms.ModelChoiceField(
        label="Slot",
        queryset=# Get some slots
    )
    value = forms.CharField(
        required=False,
        label=_("The slot value to save"),
    )


    def make_changes(self):
        items = self.items_to_change
        # In this method check the user has permission to edit the items
        # Then check they are all the same type and can have the requested slot
        # Then save everything
```

Then make sure an appropriate test case is written.
