### ISSUE TITLE
Admin interface - request to add functions

### ISSUE THREAD

**Issue by jadedjester** [aristotle-mdr/aristotle-metadata-registry#55]
It would be nice if there were a few more features in the drop down list in the Admin/polls screen - currently there is only a delete function.

To make it more functional you could add: bulk registration updates, bulk clone, bulk add to my favourites, bulk download :)

![admin_features](https://cloud.githubusercontent.com/assets/7429044/4431916/33575f98-467e-11e4-8e4b-a522bd84a677.jpg)

**Comment by LegoStormtroopr** [comment]
This has been superseded by the new front end administration interface and bulk-action registry. I'm going to close this for now, and explore this again at a later stage if it comes up.
