### ISSUE TITLE
bytes string in ManyToManyField definitions fails string assertion on Django 1.8 with Python3

### ISSUE THREAD

**Issue by ashleysommer** [aristotle-mdr/aristotle-metadata-registry#553]
In the Migrations directory, the migration files include creation of some models which have ManyToMany fields. These are declared with lines such as this:
```
models.ManyToManyField(related_name='input_to_derivation', to=b'aristotle_mdr.DataElement', blank=True)
```
The `to` variable is coded as a bytes-string as denoted by the `b'...'` syntax. It is passed into the `ManyToManyField` constructor as a type `bytes`.
In the constructor there is an assertion to ensure that `to` is of type `six.string_types`
```
assert isinstance(to, six.string_types)
```
In this case, `six.string_types` includes only one type, that is `str`. The `bytes` type is not considered a string and this fails.

The execution of the Migrations fails.

**Comment by LegoStormtroopr** [comment]
This should be resolved now by #563 and #579. Waiting response.
