### ISSUE TITLE
Migration 0013_concept_field_fixer_part1 references non-existent dependency

### ISSUE THREAD

**Issue by ashleysommer** [aristotle-mdr/aristotle-metadata-registry#554]
It appears that migrations 0001-to-0012 were squashed into a single migration called `0001_squashed_0012_better_workflows`, which replaces migrations 0001-to-0012.

It also appears that the original 12 migrations that were squashed have been removed from the project.

The migration file `0013_concept_field_fixer_part1` references a dependency with the line
```
    dependencies = [
        ('aristotle_mdr', '0012_better_workflows'),
    ]
```
However the dependency `0012_better_workflows` no longer exists in the project.

Django throws an error when processing this migration.

The django documentation [about squashing migrations here](https://docs.djangoproject.com/en/1.8/topics/migrations/#squashing-migrations) says that after squashing migrations, and deleting the migrations that it replaces...
```
Update all migrations that depend on the deleted migrations to depend on the squashed migration instead.
```

**Comment by LegoStormtroopr** [comment]
Which version of Django has this issue?
The current test suite tests against 1.8.x and it runs ok.

Migration `0001_squashed_0012_better_workflows` includes this line:

```
class Migration(migrations.Migration):

    replaces = [ ...  (b'aristotle_mdr', '0012_better_workflows')]
```

Which allow it to run. What is the exception?

**Comment by ashleysommer** [comment]
I'm on Django v 1.8.16
This is the exception:
```
django.db.migrations.graph.NodeNotFoundError: Migration aristotle_mdr.0013_concept_field_fixer_part1 dependencies reference nonexistent parent node ('aristotle_mdr', '0012_better_workflows')
```

This is the full stack trace:
```
Unhandled exception in thread started by <_pydev_bundle.pydev_monkey._NewThreadStartupWithTrace object at 0x7fae810ae1d0>
Traceback (most recent call last):
  File "/mnt/ssd/home/som05d/pycharm/helpers/pydev/_pydev_bundle/pydev_monkey.py", line 565, in __call__
    return self.original_func(*self.args, **self.kwargs)
  File "/home/som05d/venv/aris/lib/python3.5/site-packages/django/utils/autoreload.py", line 229, in wrapper
    fn(*args, **kwargs)
  File "/home/som05d/venv/aris/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 116, in inner_run
    self.check_migrations()
  File "/home/som05d/venv/aris/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 168, in check_migrations
    executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
  File "/home/som05d/venv/aris/lib/python3.5/site-packages/django/db/migrations/executor.py", line 19, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/home/som05d/venv/aris/lib/python3.5/site-packages/django/db/migrations/loader.py", line 47, in __init__
    self.build_graph()
  File "/home/som05d/venv/aris/lib/python3.5/site-packages/django/db/migrations/loader.py", line 308, in build_graph
    _reraise_missing_dependency(migration, parent, e)
  File "/home/som05d/venv/aris/lib/python3.5/site-packages/django/db/migrations/loader.py", line 291, in _reraise_missing_dependency
    raise exc
  File "/home/som05d/venv/aris/lib/python3.5/site-packages/django/db/migrations/loader.py", line 301, in build_graph
    self.graph.add_dependency(migration, key, parent)
  File "/home/som05d/venv/aris/lib/python3.5/site-packages/django/db/migrations/graph.py", line 116, in add_dependency
    parent
django.db.migrations.graph.NodeNotFoundError: Migration aristotle_mdr.0013_concept_field_fixer_part1 dependencies reference nonexistent parent node ('aristotle_mdr', '0012_better_workflows')
```

**Comment by LegoStormtroopr** [comment]
Hmmm... thats unusual. This travis-ci test suite ran with Django 1.8.16 and worked ok.

https://travis-ci.org/aristotle-mdr/aristotle-metadata-registry/jobs/174671484

I should be a straight forward fix, I'm just curious to know why that happened.

**Comment by LegoStormtroopr** [comment]
Ah! You are running Python 3. Aristotle doesn't support Python 3 yet. When the project started, we had some dependencies on Py2 only libraries which I'm slowly excising.

**Comment by ashleysommer** [comment]
Ok. Thanks.
I thought that might be it, but it is still interesting that using python 3 would manifest with this problem.

**Comment by ashleysommer** [comment]
Found another one.
In `contrib/slots/migrations/0001_initial`
```
    dependencies = [
        ('aristotle_mdr', '0011_update_ckeditor_remove_d19_errors'),
    ]
```
Should also be changed to `0001_squashed_0012_better_workflows`.

**Comment by LegoStormtroopr** [comment]
FYI I'm doing a big Python 3 update right now, most of the required libraries have been updated. So I'll address this bug in PR #563

**Comment by LegoStormtroopr** [comment]
@ashleysommer Can you confirm this is still an issue? The develop branch is now Python3 compatible and has passed a round of Python3 tests including migrations.

**Comment by LegoStormtroopr** [comment]
@ashleysommer I've tested this against Python 2 and 3 and Django 1.8 and 1.10 on Windows and Linux and can't replicate this. Can you provide any more details on this?
