### ISSUE TITLE
Key Error in /search

### ISSUE THREAD

**Issue by ashleysommer** [aristotle-mdr/aristotle-metadata-registry#560]
This is demonstrated on the example registry here: http://aristotle.pythonanywhere.com/search?q=example
On that search page, in the left-hand filter menu, under Registration Authority click 'Not registered' or under Status click 'Not registered', you will see a `KeyError` exception thrown.

**Comment by LegoStormtroopr** [comment]
This should have been fixed in #573 but I'll confirm.
