### ISSUE TITLE
broken link on website

### ISSUE THREAD

**Issue by vdubya** [aristotle-mdr/aristotle-metadata-registry#585]
The "Try It Now" button on the home page at http://aristotlemetadata.com/ has a typo (an extra "t").

"http://registry.aristotltemetadata.com/" should be "http://registry.aristotlemetadata.com/"

**Comment by LegoStormtroopr** [comment]
Thanks very much for letting us know. I'll fix it shortly.

**Comment by vdubya** [comment]
@LegoStormtroopr No problem. Definitely an important link to ensure is working!

**Comment by LegoStormtroopr** [comment]
And fixed. Thanks again for finding it, and reporting it.

**Comment by LegoStormtroopr** [comment]
Also, I'm keen to hear about your experiences with the rest of the site, and your interest in metadata.

I've got an email in my profile if you want to get in touch with me or the rest of the team.
