### ISSUE TITLE
Register bulk action fails when there are no RAs

### ISSUE THREAD

**Issue by LegoStormtroopr** [aristotle-mdr/aristotle-metadata-registry#647]

**Comment by s-i-l-k-e** [comment]
Thanks for reporting @LegoStormtroopr 
![image](https://user-images.githubusercontent.com/38807135/72028337-37df6980-32d6-11ea-9adc-869e80d56322.png)

**Comment by s-i-l-k-e** [comment]
Due for release 3.0.14.
