### ISSUE TITLE
Improve item editor

### ISSUE THREAD

**Issue by LegoStormtroopr** [aristotle-mdr/aristotle-metadata-registry#656]
All parts of an item should be editable from the one page (except for statuses).

Having to edit weak related items (such as permissible values or data element inclusions) via a different window is unintuitive.

**Comment by s-i-l-k-e** [comment]
![image](https://user-images.githubusercontent.com/38807135/61272038-78f43680-a7e9-11e9-9c45-596003b01fce.png)
