### ISSUE TITLE
can't read particular character in downloaded pdf

### ISSUE THREAD

**Issue by ho9science** [aristotle-mdr/aristotle-metadata-registry#691]
I saved metadata in Korean

but I downloaded pdf, can not read Korean metadata description

It just like "■■■■■■■"

May I figure it out how convert to readable Korean?

**Comment by LegoStormtroopr** [comment]
weasyprint probably has better support for unicode, and there is details on how to generate tables of contents from it now, so I'll see if I can move the downloads to weasyprint

https://github.com/Kozea/WeasyPrint/issues/23#issuecomment-312447974

**Comment by LegoStormtroopr** [comment]
We now use weazy print in version 1.6 and above, can you check if this is still an issue?

**Comment by ho9science** [comment]
Thank you for your kindness
In fact, I solved this issue using link_callback in xhtml2pdf.
