### ISSUE TITLE
Rewrite workgroup view methods to use Class based views

### ISSUE THREAD

**Issue by LegoStormtroopr** [aristotle-mdr/aristotle-metadata-registry#705]
aristotle_mdr.views.workgroups would be much cleaner using Class-based Views.

This should be a straight forward and small refactor, without any need to change templates or tests.

Read more about Class-based views here.
https://ccbv.co.uk/projects/Django/1.10/

**Comment by DeKaN** [comment]
I'm going to do this

**Comment by LegoStormtroopr** [comment]
Thank @DeKaN !

**Comment by DeKaN** [comment]
@LegoStormtroopr some of mixins were added in Django 1.9, but your project uses 1.8 as minimum version. Can I increase minimum version? (I may use backport library else)

**Comment by LegoStormtroopr** [comment]
We need to support 1.8 and 1.10 for a little bit longer.

if you can backport and comment where you've done so that'd be great.

**Comment by DeKaN** [comment]
LoginRequiredMixin already backported in django-braces library

**Comment by LegoStormtroopr** [comment]
Sounds good. Go for it :)

**Comment by LegoStormtroopr** [comment]
This was closed by #706
