### ISSUE TITLE
Rewrite discussions view methods to use Class based views

### ISSUE THREAD

**Issue by LegoStormtroopr** [aristotle-mdr/aristotle-metadata-registry#708]
aristotle_mdr.views.discussions would be much cleaner using Class-based Views.

This should be a straight forward and small refactor, without any need to change templates or tests.

See issue #705 for more details on how to do this.

Read more about Class-based views here.
https://ccbv.co.uk/projects/Django/1.10/

**Comment by itepifanio** [comment]
Working on it
