### ISSUE TITLE
Rewrite user management view methods to use Class based views

### ISSUE THREAD

**Issue by LegoStormtroopr** [aristotle-mdr/aristotle-metadata-registry#710]
`aristotle_mdr.views.user_pages` would be much cleaner using Class-based Views.

This should be a straight forward and small refactor, without any need to change templates or tests.

See issue #705 for more details on how to do this.

Read more about Class-based views here.
https://ccbv.co.uk/projects/Django/1.10/

**Comment by DeKaN** [comment]
I can help with it :)

**Comment by DeKaN** [comment]
@derrix060 I have finished it, fixing tests

**Comment by samie820** [comment]
Let me jump on this since its still open, hope I am welcome

**Comment by LegoStormtroopr** [comment]
I don't think the original pull was ever pulled in, and its a bit out of date now.

Happy for you to address this, and PR #711 is a good place to start.
