### ISSUE TITLE
Advanced search - does not return specific item types if no search term entered. 

### ISSUE THREAD

**Issue by traciwilson** [aristotle-mdr/aristotle-metadata-registry#712]
In advanced search, it would be helpful to be able to search for all of one particular item type without a search term.

For example, select a particular item type (type = data elements) and leave the search box blank. Search should return all data elements and no other item types. However, search returns all item types (data elements, indicators, value domains, etc.). 

https://registry.aristotlemetadata.com/search?q=&models=aristotle_mdr.dataelement&mq=&mds=&mde=&cq=&cds=&cde=&sort=n

**Comment by LegoStormtroopr** [comment]
Thanks for addressing this, that is an reasonable expectation of how the search box should work.
We have a new version coming out shortly, and should be able to squeeze this into the next release.

In the interim, there is https://registry.aristotlemetadata.com/browse/aristotle_mdr/dataelement
