### ISSUE TITLE
Browse page pagination doesn't show the current page

### ISSUE THREAD

**Issue by LegoStormtroopr** [aristotle-mdr/aristotle-metadata-registry#714]
For example on page for of this browse section page 4 isn't hilgihted

https://registry.aristotlemetadata.com/browse/aristotle_mdr/objectclass?page=4

![image](https://user-images.githubusercontent.com/2173174/31695893-dd279c14-b3f8-11e7-8f85-ee3548c5d0ed.png)

**Comment by SillySam** [comment]
What do you mean, please explain more

**Comment by LegoStormtroopr** [comment]
Ah, sorry. If you go to that link in the URL it shows you are on page 4, but at the bottom of the page, the option to click page 4 is still there. So there is no visual indicator of what page you are on.

The code for that set of buttons in the screen shot is generated in this template:
https://github.com/aristotle-mdr/aristotle-metadata-registry/blob/develop/aristotle_mdr/templates/aristotle_mdr/helpers/paginator.html

And uses the bootstrap pagination here:
https://getbootstrap.com/docs/3.3/components/#pagination

That tempalte should be updated to make sure the link for the current page is disabled.

**Comment by ryanermita** [comment]
yo! @LegoStormtroopr i will look into it.
