### ISSUE TITLE
Underscores between words when editing items

### ISSUE THREAD

**Issue by larrn** [aristotle-mdr/aristotle-metadata-registry#742]
Tried to add a "conceptual domain" to a DEC and the pop-up box had words that looked like this.

![image](https://user-images.githubusercontent.com/16367069/33106088-aafc5656-cf84-11e7-8203-0de6f8a6868d.png)

**Comment by harrywhite4** [comment]
Similar thing shows up when editing a data element on components tab

**Comment by LegoStormtroopr** [comment]
Looks like this is being pull from the help text that has been copied from the 11179 spec itself.

This is easy to change - but will cause a new set of migrations which I'm holding off from for a little longer. Keep tagging where these are happening though.

**Comment by s-i-l-k-e** [comment]
This has been fixed by moving to a single unified editor. Closing...
