### ISSUE TITLE
where is manage.py?

### ISSUE THREAD

**Issue by ho9science** [aristotle-mdr/aristotle-metadata-registry#837]
In git repository , It does not have manage.py.
I want to test mdr 2.0 in local env using git.
Do I have to using [this](https://github.com/aristotle-mdr/aristotle-metadata-registry/releases/tag/2.0.0-rc1)?

**Comment by LegoStormtroopr** [comment]
Is this for development or production?

I've just updated the develop branch so that should help with development and testing work with the new docker development environment - https://github.com/aristotle-mdr/aristotle-metadata-registry/tree/develop/docker

**Comment by ho9science** [comment]
It works well.
Thanks
by the way, which branch should I use to use the current version? develop? master?

**Comment by LegoStormtroopr** [comment]
Master is the branch that contains the latest fully tested and stable release.

Develop is the branch for the next upcoming version - but has also undergone continuous integration testing, but features may change as we develop them. If you don't mind running on the bleeding edge this is fine to use for evaluating new releases.
