### ISSUE TITLE
Builds are failing on appveyor.

### ISSUE THREAD

**Issue by derrix060** [aristotle-mdr/aristotle-metadata-registry#840]
I've noticed that there is a Badge saying that the build has failed on appveyor, and looking the [history](https://ci.appveyor.com/project/LegoStormtroopr/aristotle-metadata-registry-361e5/history) looks like it's using a old version from the tests.

This issue is to fix the problem or only remove the badge if it doesn't make sense to have.

**Comment by LegoStormtroopr** [comment]
Happy for to make a PR removing the badge from the root README file, otherwise I'll get to it this week.

Cheers.
