### ISSUE TITLE
django.template.exceptions.TemplateSyntaxError: 'live_notify_badge' received unexpected keyword argument 'classes'

### ISSUE THREAD

**Issue by ho9science** [aristotle-mdr/aristotle-metadata-registry#849]
me env is
> ubuntu 16
> python3.5.2

I checkout branch master, and following step.
`pip install aristotle-metadata-registry`
`pip install Whoosh`
`python manage.py migrate`
`python manage.py collectstatic`
`python manage.py runserver`
`http://localhost:8000`

but error in 152line, aristotle_mdr/header.html:
`{% live_notify_badge badge_class="badge" %}`
`django.template.exceptions.TemplateSyntaxError: 'live_notify_badge' received unexpected keyword argument 'classes'`

and I modified code as next. [here(develop branch source code)](https://github.com/aristotle-mdr/aristotle-metadata-registry/blob/564febcaa63ba9f38d677dfe88fa722c4a782700/python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/header.html)
`{% live_notify_badge badge_class="badge notify-badge" %}
                </a>
 {% live_notify_list list_class="dropdown-menu notify-menu" %}`

but error in 44line, aristotle_mdr/header.html:
`<a href="{% url 'browse_apps' %}">{% trans 'Browse'%}</a>`

and I modified code as next adding, aristotle_mdr/usrls/__init__.py.

`url(r'^', include('aristotle_mdr.contrib.browse.urls', app_name="aristotle_mdr", namespace="browse_apps")),`

but another error occrured.

I can't figure out it solution problem. what do I do? please.

**Comment by harrywhite4** [comment]
Hey, the first issue is due to a change in a package we are using. To fix the issue you can either install django-notifications-hq 1.3 with ``pip install django-notifications-hq==1.3`` or use the develop branch

If you want to get a local version running quickly you can use the easy installer by runnning ``aristotle-easy-installer`` once the pip package is installed (you will still have to manually install notifications 1.3 though)

**Comment by ho9science** [comment]
I used  [mdr2.0](https://github.com/aristotle-mdr/aristotle-metadata-registry/releases/tag/2.0.0-rc1)
`python setup.py install`
`pip uninstall django-notifications-hq`
`pip install django-notifications-hq==1.3`
and
I have modified 
aristotle-metadata-registry/python/aristotle-metadata-registry/aristotle_mdr/urls/__init__.py
as [develop branch code](https://github.com/aristotle-mdr/aristotle-metadata-registry/blob/develop/python/aristotle-metadata-registry/aristotle_mdr/urls/__init__.py)
```
urlpatterns = [     
    url(r'^', include('aristotle_mdr.urls.base')),  
    url(r'^browse/', include('aristotle_mdr.contrib.browse.urls')),
    url(r'^help/', include('aristotle_mdr.contrib.help.urls', app_name="aristotle_help", namespace="aristotle_help")),
    url(r'^', include('aristotle_mdr.contrib.user_management.urls', namespace="aristotle-user")),
    url(r'^', include('aristotle_mdr.urls.aristotle', app_name="aristotle_mdr", namespace="aristotle")),
    url(r'^ac/', include('aristotle_mdr.contrib.autocomplete.urls', namespace="aristotle-autocomplete")),
    url(r'^', include('aristotle_mdr.contrib.healthcheck.urls', app_name="aristotle_mdr_hb", namespace="aristotle_hb")),
]
```
it works 
thank you for your help
