### ISSUE TITLE
Missing bootstrap css classes on password reset field

### ISSUE THREAD

**Issue by borsna** [aristotle-mdr/aristotle-metadata-registry#926]
Eg:
https://ddi-alliance.aristotlecloud.io/user/password/reset/
![image](https://user-images.githubusercontent.com/794445/46157116-4f2e4b00-c27b-11e8-9804-50d53ca0048f.png)

**Comment by borsna** [comment]
Also on the reset password form for  password fields and submit button:
![image](https://user-images.githubusercontent.com/794445/46157306-b0eeb500-c27b-11e8-94bb-7a11d3c31b67.png)

**Comment by leonorader** [comment]
Hi!
I would like to work on this! :)

**Comment by LegoStormtroopr** [comment]
@leonorader We'd be happy to have your help!

**Comment by s-i-l-k-e** [comment]
@LegoStormtroopr thanks for reporting. Due for release 3.0.14.
