### ISSUE TITLE
Change roles leads nowhere

### ISSUE THREAD

**Issue by jfihn** [aristotle-mdr/aristotle-metadata-registry#938]
![image](https://user-images.githubusercontent.com/3796730/46609737-20309880-cb09-11e8-94eb-1a7335d80b62.png)

Clicking "Change roles" is a dead end.

**Comment by LegoStormtroopr** [comment]
Thanks for reporting @jfihn. That link loads a javascript modal, to help triage this can you answer a few questions?
* If you right-click and select "open in a new window", does the page load then?
* What browser are you using?
* If you clear your cache and reload the page does the issue still happen?

**Comment by jfihn** [comment]
If I open in a new window I get "Forbidden", which probably is the cause of the problem. I use Chrome.

**Comment by s-i-l-k-e** [comment]
This has been fixed as part of a resolution of permissions.
