### ISSUE TITLE
User should be able to search for discussions

### ISSUE THREAD

**Issue by LegoStormtroopr** [aristotle-mdr/aristotle-metadata-registry#941]
A user when searching should be able to get results for relevant discussions.

A discussion index should include the workgroup and only return a result when the user is in the appropriate workgroup

**Comment by smritigambhir** [comment]
Hi @LegoStormtroopr 
What discussions are you referring to? Do you want to build search functionality for the Aristotle MDR blog?

**Comment by LegoStormtroopr** [comment]
Within Aristotle itself, we have the ability for users to post discussions

These are managd currently in `models.py`:

https://github.com/aristotle-mdr/aristotle-metadata-registry/blob/develop/python/aristotle-metadata-registry/aristotle_mdr/models.py#L583

A discussion post belongs to a "Workgroup", which is one of the ways we scope visibility in Aristotle.

It would be good if these were indexed in `search_indexes.py`:

https://github.com/aristotle-mdr/aristotle-metadata-registry/blob/develop/python/aristotle-metadata-registry/aristotle_mdr/search_indexes.py

As long as the index for a discussion includes the workgroup, then the current permissions checks should work, but you'll want to test to confirm this:

https://github.com/aristotle-mdr/aristotle-metadata-registry/blob/develop/python/aristotle-metadata-registry/aristotle_mdr/forms/search.py

I hope that helps, let me know if you are interested or have more questions, and Happy Hacktoberfest!

**Comment by chrislupdx** [comment]
@LegoStormtroopr Hey! Was this taken yet?

**Comment by LegoStormtroopr** [comment]
@chrislupdx Not yet, happy for you to have a go at it.
