### ISSUE TITLE
Cannot edit Value Domain and Permissible Values

### ISSUE THREAD

**Issue by rknowles9** [aristotle-mdr/aristotle-metadata-registry#954]
Having some edit problems with Aristotle 2.0.0
- In Firefox 60.1 on Windows and 60.2 on Linux I can enter edit page from 'Permissible Values [edit]' or 'Actions->Open item editor->Components-> Edit Permissible Value'. In both cases I can make changes but when I 'Save', nothing is changed.
- In IE 11.285, same as Firefox.
- In MS Edge 42.17134 'Actions' shows no drop down, so cannot edit from there. I can edit from 'Permissible Values [edit]' and these edits are saved, but there is no drag handle for the items, so I cannot reorder them.

**Comment by rknowles9** [comment]
And ...
- In Firefox and IE I can add a permissible value, but not delete one.
- in Edge, I can delete a value, but the 'Add a code' button does not do anything.

**Comment by LegoStormtroopr** [comment]
We've fixed quite a few problems with the javascript editors, since that release.
Can you try a newer version of Aristotle to see if that fixes this?

**Comment by rknowles9** [comment]
I upgraded to 2.1.3. Firefox seems to be working fine now. Still problems with IE and Edge, but I can happily continue working in Firefox. Thanks!

**Comment by LegoStormtroopr** [comment]
Great to hear. We have a new release in the pipeline with fixes for IE & Edge, so I'll leave this open for now.

We're always curious to hear about people using the platform, so feel free to email me - my email details are on my profile page.

**Comment by LegoStormtroopr** [comment]
@rknowles9 is this still a probem in IE?

**Comment by Rknowles0** [comment]
Now working in IE, Firefox, and Edge.
