### ISSUE TITLE
Dataset page shouldnt show distribution details if there are none

### ISSUE THREAD

**Issue by LegoStormtroopr** [aristotle-mdr/aristotle-metadata-registry#967]
![image](https://user-images.githubusercontent.com/2173174/47277245-d9af6380-d609-11e8-8af4-522bf3717c84.png)

**Comment by s-i-l-k-e** [comment]
@LegoStormtroopr, thanks for reporting. This has been fixed.
![image](https://user-images.githubusercontent.com/38807135/72571417-9f6b6980-3913-11ea-8f89-3a4978839012.png)
